spring:
  datasource:
      url: jdbc:mysql://localhost:3306/big_event
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
     map-underscore-to-camel-case: true  # 驼峰命名规则和下划线命名规则转换